Add set -e flag.

diff --git a/scripts/hello b/scripts/hello
--- a/scripts/hello
+++ b/scripts/hello
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+set -e  # Exit immediately if a command exits with a non-zero status.
+
 say_hello() {
   echo "Hello"
   echo "How are you?"
diff --git a/scripts/spacetodash b/scripts/spacetodash
--- a/scripts/spacetodash
+++ b/scripts/spacetodash
@@ -1,4 +1,7 @@
 #!/bin/bash
+
+set -e  # Exit immediately if a command exits with a non-zero status.
+
 # This would be for renaming all files in a directory
 # for file in *; do mv "$file" $(echo $file | tr ' ' '-') ; done
 if test -f "$1"; then
